using System;
using System.Collections.Generic;
using System.Globalization;
namespace Shift.Game
{
    public static class LocalizationCatalog
    {
        private static readonly Dictionary<string, string[]> entries = new Dictionary<string, string[]>
        {
            { "hud.level_badge", new[] { "LEVEL {0}", "BÖLÜM {0}" } },
            { "ending.complete", new[] { "CAMPAIGN COMPLETE", "KAMPANYA TAMAMLANDI" } },
            { "ending.complete_body", new[] { "40 puzzles solved.\nEvery system connected.", "40 bulmaca tamamlandı.\nTüm sistem birbirine bağlandı." } },
            { "ending.perfect_final", new[] { "PERFECT FINAL SHIFT", "KUSURSUZ SON SHIFT" } },
            { "ending.mastered", new[] { "CAMPAIGN MASTERED", "KAMPANYADA USTALAŞTIN" } },
            { "ending.quote", new[] { "You learned the rules.\nThen you learned how to bend them.", "Kuralları öğrendin.\nSonra onları nasıl esneteceğini öğrendin." } },
            { "ending.summary", new[] { "40 / 40 COMPLETED\nPerfect Shift: {0} / 40\nDaily Shift: Available every day", "40 / 40 TAMAMLANDI\nPerfect Shift: {0} / 40\nGünün SHIFT’i: Her gün yeni bulmaca" } },
            { "ending.body", new[] { "The campaign is complete.\nEvery puzzle still has its cleanest solution.\nReturn for Daily Shift,\nor perfect the levels you left behind.", "Kampanya tamamlandı.\nHer bulmacanın hâlâ en temiz çözümü var.\nGünün SHIFT’i için geri dön\nveya kalan bölümlerde Perfect Shift’i tamamla." } },
            { "ending.mastered_body", new[] { "Every puzzle. Its cleanest solution.\nReturn for Daily Shift,\nor enjoy the campaign again.", "Her bulmacada en temiz çözümü buldun.\nGünün SHIFT’i için geri dön\nveya kampanyayı yeniden oyna." } },
            { "ending.continue", new[] { "CONTINUE", "DEVAM" } },
            { "ending.mastery", new[] { "REVIEW MASTERY", "USTALIĞI GÖR" } },
            { "ending.daily", new[] { "DAILY SHIFT", "GÜNÜN SHIFT’İ" } },
            { "ending.replay", new[] { "REPLAY LEVELS", "BÖLÜMLERİ TEKRAR OYNA" } },
            { "ending.levels", new[] { "BACK TO LEVELS", "BÖLÜMLERE DÖN" } },
            { "resume.continue", new[] { "Continue", "Devam Et" } },
            { "resume.continue_level", new[] { "Continue Level {0}", "{0}. Bölüme Devam Et" } },
            { "resume.mastery", new[] { "Review Mastery", "Ustalık Durumunu Gör" } },
            { "resume.daily_unavailable", new[] { "Daily Shift unavailable", "Günün SHIFT'i şu anda kullanılamıyor" } },
            { "resume.no_levels", new[] { "Campaign unavailable. Please reopen SHIFT.", "Kampanya kullanılamıyor. Lütfen SHIFT'i yeniden aç." } },
            { "onboarding.welcome.title", new[] { "WELCOME TO SHIFT", "SHIFT'E HOŞ GELDİN" } },
            { "onboarding.welcome.subtitle", new[] { "Small puzzles. One-finger control.\nSatisfying chain reactions.", "Kısa bulmacalar. Tek parmak kontrol.\nTatmin edici zincir reaksiyonları." } },
            { "onboarding.welcome.levels", new[] { "40 handcrafted levels", "40 el yapımı seviye" } },
            { "onboarding.welcome.daily", new[] { "A new Daily Shift every day", "Günün SHIFT'i ile her gün yeni bulmaca" } },
            { "onboarding.welcome.perfect", new[] { "Master the most efficient solution with Perfect Shift", "Perfect Shift ile en iyi çözümü bul" } },
            { "onboarding.how.title", new[] { "HOW TO PLAY", "NASIL OYNANIR" } },
            { "onboarding.how.subtitle", new[] { "Simple at first.\nThe right order makes the system work.", "Basit görünür.\nDoğru sırayı bulunca sistem çalışır." } },
            { "onboarding.how.move", new[] { "Move the piece", "Diski hareket ettir" } },
            { "onboarding.how.direction", new[] { "Follow its direction", "Ok yönünü takip et" } },
            { "onboarding.how.exit", new[] { "Guide each color to its exit", "Rengi doğru çıkışa ulaştır" } },
            { "onboarding.how.tip", new[] { "Make space first. Then start the chain.", "Önce alan aç. Sonra zinciri başlat." } },
            { "onboarding.chain.title", new[] { "BUILD THE CHAIN", "ZİNCİRİ KUR" } },
            { "onboarding.chain.subtitle", new[] { "The best solutions think beyond one move.", "En iyi çözümler tek hamleden fazlasını düşünür." } },
            { "onboarding.chain.reaction", new[] { "Every move can trigger a new reaction.", "Her hamle yeni bir tepki başlatabilir." } },
            { "onboarding.chain.perfect", new[] { "Perfect Shift rewards the most efficient solution.", "Perfect Shift en verimli çözümü ödüllendirir." } },
            { "onboarding.chain.help", new[] { "If you get stuck, Hint and Undo are there.", "Takılırsan İpucu ve Geri Al yanında." } },
            { "onboarding.ready.title", new[] { "READY?", "HAZIRSAN BAŞLA" } },
            { "onboarding.ready.subtitle", new[] { "Start with the first puzzle.\nCome back for Daily Shift and chase Perfect solutions.", "İlk bulmacayla başla.\nGünün SHIFT'i için geri gel ve Perfect çözümleri kovala." } },
            { "onboarding.ready.campaign", new[] { "40-level campaign", "40 seviyelik kampanya" } },
            { "onboarding.ready.daily", new[] { "A new Daily Shift every day", "Her gün yeni Günün SHIFT'i" } },
            { "onboarding.skip", new[] { "SKIP", "ATLA" } },
            { "onboarding.back", new[] { "BACK", "GERİ" } },
            { "onboarding.continue", new[] { "CONTINUE", "DEVAM" } },
            { "onboarding.start", new[] { "LET'S START", "BAŞLAYALIM" } },
            { "onboarding.play", new[] { "PLAY NOW", "OYUNA BAŞLA" } },
            { "settings.privacy_choices", new[] { "Privacy Choices", "Gizlilik Tercihleri" } },
            { "settings.title", new[] { "SETTINGS", "AYARLAR" } },
            { "settings.sound_on", new[] { "SOUND: ON", "SES: AÇIK" } },
            { "settings.sound_off", new[] { "SOUND: OFF", "SES: KAPALI" } },
            { "settings.haptics_on", new[] { "HAPTICS: ON", "TİTREŞİM: AÇIK" } },
            { "settings.haptics_off", new[] { "HAPTICS: OFF", "TİTREŞİM: KAPALI" } },
            { "settings.reduced_on", new[] { "REDUCED MOTION: ON", "AZALTILMIŞ HAREKET: AÇIK" } },
            { "settings.reduced_off", new[] { "REDUCED MOTION: OFF", "AZALTILMIŞ HAREKET: KAPALI" } },
            { "settings.language", new[] { "LANGUAGE: ENGLISH", "DİL: TÜRKÇE" } },
            { "common.back", new[] { "BACK", "GERİ" } },
            { "common.back_title", new[] { "Back", "Geri" } },
            { "hud.moves", new[] { "Moves:", "Hamle:" } },
            { "objective.Red", new[] { "Clear Red", "Kırmızıyı temizle" } },
            { "objective.Blue", new[] { "Clear Blue", "Maviyi temizle" } },
            { "objective.Green", new[] { "Clear Green", "Yeşili temizle" } },
            { "objective.Yellow", new[] { "Clear Yellow", "Sarıyı temizle" } },
            { "objective.both", new[] { "Clear Both", "İkisini temizle" } },
            { "objective.all", new[] { "Clear All", "Hepsini temizle" } },
            { "controls.undo", new[] { "Undo", "Geri Al" } },
            { "controls.restart", new[] { "Restart", "Yeniden" } },
            { "controls.hint", new[] { "Hint", "İpucu" } },
            { "controls.levels", new[] { "Levels", "Bölümler" } },
            { "results.replay", new[] { "Replay", "Tekrar Oyna" } },
            { "results.retry", new[] { "Retry", "Tekrar Dene" } },
            { "results.next", new[] { "Next Level", "Sonraki Bulmaca" } },
            { "results.goal", new[] { "GOAL COMPLETE!\nBeautiful chain. Play again?", "HEDEF TAMAMLANDI!\nGüzel zincir. Tekrar oynayalım mı?" } },
            { "results.ready", new[] { "GOAL COMPLETE!\nReady for the next puzzle?", "HEDEF TAMAMLANDI!\nSıradaki bulmacaya hazır mısın?" } },
            { "results.chapter1", new[] { "CHAPTER COMPLETE!\nChapter 2 is ready.", "BÖLÜM TAMAMLANDI!\n2. Bölüm hazır." } },
            { "results.chapter2", new[] { "CHAPTER 2 COMPLETE!\nSmall moves. Big reactions.", "2. BÖLÜM TAMAMLANDI!\nKüçük hamleler. Büyük etkiler." } },
            { "results.chapter_title1", new[] { "CHAPTER COMPLETE!", "BÖLÜM TAMAMLANDI!" } },
            { "results.chapter_title2", new[] { "CHAPTER 2 COMPLETE!", "2. BÖLÜM TAMAMLANDI!" } },
            { "results.lost", new[] { "OUT OF MOVES\nOne more try?", "HAMLE KALMADI\nBir daha deneyelim mi?" } },
            { "hud.blocked", new[] { "Blocked · no move used", "Yol kapalı · hamle harcanmadı" } },
            { "hud.loop", new[] { "Loop cancelled · no move used", "Döngü durduruldu · hamle harcanmadı" } },
            { "hud.reacting", new[] { "CHAIN REACTION", "ZİNCİR TEPKİMESİ" } },
            { "hud.instruction", new[] { "Tap a circle. Push pieces into an exit.", "Bir taşa dokun. Taşları çıkışa yönlendir." } },
            { "hint.exhausted", new[] { "No more hints available.", "Başka ipucu yok." } },
            { "hint.stage", new[] { "Hint {0}/3 - {1}", "İpucu {0}/3 - {1}" } },
            { "hint.fallback", new[] { "Trace the next landing. Which space will the other pieces need?", "Bir sonraki varış noktasını düşün. Diğer taşlara nerede yer gerekecek?" } },
            { "chain.Chain", new[] { "CHAIN", "ZİNCİR" } },
            { "chain.BigShift", new[] { "BIG SHIFT", "BÜYÜK SHIFT" } },
            { "chain.MegaShift", new[] { "MEGA SHIFT", "MEGA SHIFT" } },
            { "chain.Normal", new[] { "", "" } },
            { "tile.exit", new[] { "EXIT", "ÇIKIŞ" } },
            { "chapter.title", new[] { "CHAPTER {0}", "BÖLÜM {0}" } },
            { "chapter.play", new[] { "PLAY CURRENT LEVEL", "SIRADAKİ BULMACAYI OYNA" } },
            { "level.play", new[] { "PLAY", "OYNA" } },
            { "level.locked", new[] { "LOCKED", "KİLİTLİ" } },
            { "level.done", new[] { "DONE", "BİTTİ" } },
            { "mastery.first", new[] { "NEW PERFECT SHIFT", "YENİ PERFECT SHIFT" } },
            { "mastery.perfect", new[] { "PERFECT SHIFT", "PERFECT SHIFT" } },
            { "mastery.mastered", new[] { "CHAPTER MASTERED", "BÖLÜMDE USTALAŞILDI" } },
            { "mastery.summary", new[] { "{0}/{1} Complete · {2}/{1} Perfect Shift", "{0}/{1} Tamamlandı · {2}/{1} Perfect Shift" } },
            { "mastery.remaining", new[] { "{0} puzzles can still be perfected.", "{0} bulmacada daha Perfect Shift yapılabilir." } },
            { "mastery.legend", new[] { "✓ Complete    ◆ Perfect Shift", "✓ Tamamlandı    ◆ Perfect Shift" } },
            { "daily.title", new[] { "DAILY SHIFT", "GÜNÜN SHIFT'İ" } },
            { "daily.today", new[] { "Today", "Bugün" } },
            { "daily.completed", new[] { "✓ Completed", "✓ Tamamlandı" } },
            { "daily.perfect_state", new[] { "◆ Perfect Shift", "◆ Perfect Shift" } },
            { "daily.puzzle", new[] { "Today's Puzzle", "Bugünün Bulmacası" } },
            { "daily.archive", new[] { "Last 7 Days", "Son 7 Gün" } },
            { "daily.complete", new[] { "DAILY SHIFT COMPLETE", "GÜNÜN SHIFT'İ TAMAMLANDI" } },
            { "daily.perfect", new[] { "DAILY PERFECT SHIFT", "GÜNLÜK PERFECT SHIFT" } },
            { "daily.back", new[] { "Back to Daily", "Günlüğe Dön" } },
            { "reward.hint_title", new[] { "Need another hint?", "Bir ipucu daha mı lazım?" } },
            { "reward.undo_title", new[] { "Need another Undo?", "Bir geri alma hakkı daha mı lazım?" } },
            { "reward.hint_primary", new[] { "Watch Ad for +{0} Hint", "+{0} İpucu için Reklam İzle" } },
            { "reward.undo_primary", new[] { "Watch Ad for +{0} Undo", "+{0} Geri Alma için Reklam İzle" } },
            { "reward.cancel", new[] { "Not now", "Şimdi değil" } },
            { "reward.failed", new[] { "No reward received. Please try again later.", "Ödül alınamadı. Daha sonra tekrar dene." } },
            { "reward.undo_ready", new[] { "Watch an ad to get +{0} Undo.", "+{0} geri alma hakkı için reklam izle." } },
            { "reward.hint_ready", new[] { "Complete a rewarded ad to reveal the next hint.", "Sıradaki ipucu için ödüllü reklamı tamamla." } },
            { "reward.unavailable", new[] { "Ad not ready yet.", "Reklam henüz hazır değil." } },
            { "reward.pending", new[] { "Waiting for the reward result…", "Reklam sonucu bekleniyor…" } },
            { "level.Level01_FirstTap.title", new[] { "01 · First tap", "01 · İlk Dokunuş" } },
            { "level.Level01_FirstTap.instruction", new[] { "Tap Red. Follow the arrow.", "Kırmızıya dokun. Oku takip et." } },
            { "level.Level02_FindTheExit.title", new[] { "02 · Find the exit", "02 · Çıkışı Bul" } },
            { "level.Level02_FindTheExit.instruction", new[] { "Reach EXIT. Each tap moves one cell.", "Çıkışa ulaş. Her dokunuş bir kare ilerletir." } },
            { "level.Level03_ClearTheBox.title", new[] { "03 · Clear the box", "03 · Kutuyu Çek" } },
            { "level.Level03_ClearTheBox.instruction", new[] { "Yellow can push the box out of Red's path.", "Sarı, kutuyu Kırmızı'nın yolundan çekebilir." } },
            { "level.Level04_FirstChain.title", new[] { "04 · First chain", "04 · İlk Zincir" } },
            { "level.Level04_FirstChain.instruction", new[] { "One Yellow tap. Three pieces in motion.", "Sarıya bir dokunuş. Üç taş harekette." } },
            { "level.Level05_BlockedIsFree.title", new[] { "05 · Look for space", "05 · Boşluk Ara" } },
            { "level.Level05_BlockedIsFree.instruction", new[] { "Yellow is blocked. Blocked taps cost no moves.", "Sarı ilerleyemiyor. Engellenen dokunuşlar hamle harcamaz." } },
            { "level.Level06_TurnTheCorner.title", new[] { "06 · Turn the corner", "06 · Köşeyi Dön" } },
            { "level.Level06_TurnTheCorner.instruction", new[] { "The arrow tile redirects Red and adds a step.", "Ok karesi, Kırmızı'nın yönünü değiştirip bir adım daha ilerletir." } },
            { "level.Level07_MakeRoom.title", new[] { "07 · Make room", "07 · Yer Aç" } },
            { "level.Level07_MakeRoom.instruction", new[] { "Blue cannot use the red exit. Move it up first.", "Mavi, kırmızı çıkışı kullanamaz. Önce yukarı taşı." } },
            { "level.Level08_Clockwise.title", new[] { "08 · Clockwise", "08 · Saat Yönünde" } },
            { "level.Level08_Clockwise.instruction", new[] { "The rotator turns Red clockwise, then moves it.", "Döndürücü, Kırmızı'yı saat yönünde çevirip ilerletir." } },
            { "level.Level09_PushAndTurn.title", new[] { "09 · Push and turn", "09 · İt ve Dön" } },
            { "level.Level09_PushAndTurn.instruction", new[] { "Predict where Red stops after Yellow's push.", "Sarı ittiğinde Kırmızı'nın nerede duracağını düşün." } },
            { "level.Level10_SetTheChain.title", new[] { "10 · Set the chain", "10 · Zinciri Kur" } },
            { "level.Level10_SetTheChain.instruction", new[] { "Make room above the arrow before starting the chain.", "Zinciri başlatmadan önce okun üstünde yer aç." } },
            { "level.Level11_OpenTheLane.title", new[] { "11 · Open the lane", "11 · Yolu Aç" } },
            { "level.Level11_OpenTheLane.instruction", new[] { "Give Blue space before advancing Red.", "Kırmızı'yı ilerletmeden önce Mavi'ye yer aç." } },
            { "level.Level12_CrossingOrder.title", new[] { "12 · Crossing order", "12 · Geçiş Sırası" } },
            { "level.Level12_CrossingOrder.instruction", new[] { "Who should cross the corner first?", "Köşeden önce kim geçmeli?" } },
            { "level.Level13_SecondAct.title", new[] { "13 · Second act", "13 · İkinci Perde" } },
            { "level.Level13_SecondAct.instruction", new[] { "The first push prepares the second reaction.", "İlk itiş, ikinci tepkiyi hazırlar." } },
            { "level.Level14_TwoCorners.title", new[] { "14 · Two corners", "14 · İki Köşe" } },
            { "level.Level14_TwoCorners.instruction", new[] { "Trace both arrows before choosing your first tap.", "İlk dokunuşu seçmeden iki oku da takip et." } },
            { "level.Level15_TheLongSetup.title", new[] { "15 · The long setup", "15 · Uzun Hazırlık" } },
            { "level.Level15_TheLongSetup.instruction", new[] { "The obvious chain needs an empty landing cell.", "Görünen zincirin varış karesi boş olmalı." } },
            { "level.Level16_TransformAhead.title", new[] { "16 · Transform ahead", "16 · Dönüşe Hazırlan" } },
            { "level.Level16_TransformAhead.instruction", new[] { "Clockwise, then up. Predict the next corner too.", "Saat yönünde, sonra yukarı. Sonraki köşeyi de düşün." } },
            { "level.Level17_SharedCorridor.title", new[] { "17 · Shared corridor", "17 · Ortak Koridor" } },
            { "level.Level17_SharedCorridor.instruction", new[] { "Blue and Red need the same corner. Choose their order.", "Mavi ve Kırmızı aynı köşeyi kullanacak. Sıralarını seç." } },
            { "level.Level18_ClearTriggerFinish.title", new[] { "18 · Clear, trigger, finish", "18 · Aç, Başlat, Bitir" } },
            { "level.Level18_ClearTriggerFinish.instruction", new[] { "Make a parking space before moving Blue.", "Mavi'yi taşımadan önce bekleyeceği yeri aç." } },
            { "level.Level19_SharedDelivery.title", new[] { "19 · Shared delivery", "19 · Birlikte Çıkış" } },
            { "level.Level19_SharedDelivery.instruction", new[] { "Can one Red help the other reach the exit?", "Bir Kırmızı, diğerini çıkışa ulaştırabilir mi?" } },
            { "level.Level20_TheFinalShift.title", new[] { "20 · The final shift", "20 · Son Hamle" } },
            { "level.Level20_TheFinalShift.instruction", new[] { "Open the landing, then follow the turns to the finish.", "Varış karesini aç, sonra dönüşleri takip et." } },
            { "level.Level21_FirstSwitch.title", new[] { "21 - Switch Discovery", "21 - Düğmeyi Keşfet" } },
            { "level.Level21_FirstSwitch.instruction", new[] { "A circle entering a diamond pad toggles its matching gate.", "Bir taş elmaslı düğmeye girince eşleşen kapının durumu değişir." } },
            { "level.Level22_OpenForRed.title", new[] { "22 - Prepare Before Advancing", "22 - Önce Hazırla" } },
            { "level.Level22_OpenForRed.instruction", new[] { "A push changes a circle's direction. Make space before advancing.", "İtmek taşın yönünü değiştirir. İlerlemeden önce yer aç." } },
            { "level.Level23_ToggleTwice.title", new[] { "23 - Toggle Trap", "23 - Düğme Tuzağı" } },
            { "level.Level23_ToggleTwice.instruction", new[] { "Every press changes the state.", "Her basış kapının durumunu değiştirir." } },
            { "level.Level24_ClosedLane.title", new[] { "24 - Shared Passage", "24 - Ortak Geçit" } },
            { "level.Level24_ClosedLane.instruction", new[] { "Only one order keeps the passage clear.", "Geçidi yalnızca doğru sıra açık tutar." } },
            { "level.Level25_BeforeYouGo.title", new[] { "25 - Prepare the Release", "25 - Harekete Hazırla" } },
            { "level.Level25_BeforeYouGo.instruction", new[] { "Prepare before you commit.", "Harekete geçmeden önce hazırla." } },
            { "level.Level26_ThreeEntries.title", new[] { "26 - Let It Wait", "26 - Biraz Beklesin" } },
            { "level.Level26_ThreeEntries.instruction", new[] { "A clear lane starts one step away.", "Açık bir yol, bir adım ötede başlar." } },
            { "level.Level27_BoxDoesNotPress.title", new[] { "27 - Borrowed Space", "27 - Ödünç Boşluk" } },
            { "level.Level27_BoxDoesNotPress.instruction", new[] { "An empty space is not always spare.", "Her boş yer, kullanılmayan bir yer değildir." } },
            { "level.Level28_TurnThrough.title", new[] { "28 - Beyond the Turn", "28 - Dönüşün Ötesi" } },
            { "level.Level28_TurnThrough.instruction", new[] { "Look past the first turn.", "İlk dönüşün ötesine bak." } },
            { "level.Level29_ClockworkGate.title", new[] { "29 - One Move, More Work", "29 - Tek Hamle, Çok İş" } },
            { "level.Level29_ClockworkGate.instruction", new[] { "One route does more work.", "Bir yol daha çok iş görür." } },
            { "level.Level30_ClearThenOpen.title", new[] { "30 - Release the Relay", "30 - Zinciri Serbest Bırak" } },
            { "level.Level30_ClearThenOpen.instruction", new[] { "Create space. Keep the way back clear.", "Yer aç. Dönüş yolunu açık tut." } },
            { "level.Level31_OnePadTwoGates.title", new[] { "31 - Across the Divide", "31 - Öteki Tarafa" } },
            { "level.Level31_OnePadTwoGates.instruction", new[] { "What changes on the other side?", "Öteki tarafta ne değişiyor?" } },
            { "level.Level32_OppositeStates.title", new[] { "32 - Return Changed", "32 - Değişerek Dön" } },
            { "level.Level32_OppositeStates.instruction", new[] { "Some progress must come back.", "Bazen ilerlemek için geri dönmek gerekir." } },
            { "level.Level33_SharedDeliveryGate.title", new[] { "33 - A Moving Pair", "33 - Hareketli İkili" } },
            { "level.Level33_SharedDeliveryGate.instruction", new[] { "Two paths. One rhythm.", "İki yol. Tek ritim." } },
            { "level.Level34_ClearTheCorridor.title", new[] { "34 - The Easy Way", "34 - Kolay Yol" } },
            { "level.Level34_ClearTheCorridor.instruction", new[] { "Where does the easy way end?", "Kolay yol nerede bitiyor?" } },
            { "level.Level35_TwoChannels.title", new[] { "35 - Assemble the Release", "35 - Zinciri Birleştir" } },
            { "level.Level35_TwoChannels.instruction", new[] { "Build it before you fire it.", "Harekete geçirmeden önce zinciri kur." } },
            { "level.Level36_CrossBeforeClosing.title", new[] { "36 - Two Ways Through", "36 - İki Geçiş Yolu" } },
            { "level.Level36_CrossBeforeClosing.instruction", new[] { "Two colors. One turning point.", "İki renk. Tek dönüş noktası." } },
            { "level.Level37_OpenTheSecondPad.title", new[] { "37 - Borrowed Ground", "37 - Ödünç Alan" } },
            { "level.Level37_OpenTheSecondPad.instruction", new[] { "The same space, at different times.", "Aynı yer, farklı zamanlar." } },
            { "level.Level38_LiftAndTurn.title", new[] { "38 - A Favor Returned", "38 - Karşılıklı Yardım" } },
            { "level.Level38_LiftAndTurn.instruction", new[] { "Make room for each other.", "Birbirinize yer açın." } },
            { "level.Level39_PrepareToggleRedirect.title", new[] { "39 - Better Together", "39 - Birlikte Daha İyi" } },
            { "level.Level39_PrepareToggleRedirect.instruction", new[] { "Can one move do two jobs?", "Bir hamle iki iş görebilir mi?" } },
            { "level.Level40_TheStateOfShift.title", new[] { "40 - The Color Machine", "40 - Renk Makinesi" } },
            { "level.Level40_TheStateOfShift.instruction", new[] { "Build one system. Finish every color.", "Tek düzen kur. Her rengi tamamla." } },
        };
        public static IEnumerable<string> Keys => entries.Keys;
        public static bool Contains(string key) => entries.ContainsKey(key);
        public static string Format(string key, GameLanguage language, params object[] args)
        {
            if (!entries.TryGetValue(key, out var pair)) throw new ArgumentException("Unknown localization key: " + key);
            string value = pair[language == GameLanguage.Turkish ? 1 : 0];
            return args.Length == 0 ? value : string.Format(CultureInfo.GetCultureInfo(language == GameLanguage.Turkish ? "tr-TR" : "en-US"), value, args);
        }
        public static string ForHint(string key, HintLanguage language, params object[] args) => Format(key, language == HintLanguage.Turkish ? GameLanguage.Turkish : GameLanguage.English, args);
        public static string Title(LevelData level) => Contains("level." + level.name + ".title") ? GameLanguageService.Shared.Text("level." + level.name + ".title") : "SHIFT";
        public static string Instruction(LevelData level)
        {
            string key = "level." + level.name + ".instruction";
            if (Contains(key)) return GameLanguageService.Shared.Text(key);
            return GameLanguageService.Shared.CurrentLanguage == GameLanguage.English && !string.IsNullOrEmpty(level.Hint) ? level.Hint : GameLanguageService.Shared.Text("hint.fallback");
        }
    }
}
